import { EDIT_BLOGS, EDIT_IMAGE, EDIT_PROFILE } from './types';

// ACTIONS THAT TOGGLE POPUPS AND FORMS RENDERING AND BEING REMOVED

// BOOLEAN THAT SETS EDIT PROFILE CARD TO SHOW INFO OR SHOW
// FIELDS TO EDIT INFO IF TRUE
export function editProfile() {
  return {
    type: EDIT_PROFILE,
  };
}

// BOOLEAN THAT TOGGLES THE POPUP WINDOW TO EDIT PROFILE IMAGE IF TRUE
export function editImagePopup() {
  return {
    type: EDIT_IMAGE,
  };
}

// BOOLEAN THAT TOGGLES THE POPUP WINDOW TO EDIT/ADD BLOG IF TRUE
// WHETHER POPUP WILL ADD OR EDIT IS BASED ON addOrEdit BOOLEAN IN THE BLOG REDUCER/ACTIONS -ADD_OR_EDIT_BLOG
export function editBlogPopup() {
  return {
    type: EDIT_BLOGS,
  };
}
